/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register an account */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/staff-connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem a one-time connect code for a scanner-device session */
        post: operations["AuthController_staffConnect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the current user profile */
        patch: operations["AuthController_updateMe"];
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the current user password */
        patch: operations["AuthController_changePassword"];
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current signed-in session */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List upcoming published events */
        get: operations["EventsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a published event */
        get: operations["EventsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my events (any status) */
        get: operations["EventsOrganizerController_list"];
        put?: never;
        /** Create a draft event */
        post: operations["EventsOrganizerController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one of my events */
        get: operations["EventsOrganizerController_get"];
        put?: never;
        post?: never;
        /** Delete a draft event */
        delete: operations["EventsOrganizerController_remove"];
        options?: never;
        head?: never;
        /** Edit a draft event */
        patch: operations["EventsOrganizerController_update"];
        trace?: never;
    };
    "/api/organizer/events/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a draft event for Admin review (needs >= 1 ticket type) */
        post: operations["EventsOrganizerController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a pending-review or published event back to draft */
        post: operations["EventsOrganizerController_unpublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a published event */
        post: operations["EventsOrganizerController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{id}/ticket-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a ticket type */
        post: operations["EventsOrganizerController_addTicketType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{id}/ticket-types/{typeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a ticket type */
        delete: operations["EventsOrganizerController_removeTicketType"];
        options?: never;
        head?: never;
        /** Edit a ticket type */
        patch: operations["EventsOrganizerController_updateTicketType"];
        trace?: never;
    };
    "/api/me/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's issued tickets. */
        get: operations["TicketsController_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an order. Free orders are paid and issued immediately; paid orders return PENDING with VietQR payment details. */
        post: operations["OrdersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's unexpired pending orders. */
        get: operations["OrdersController_listPending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel one of the current user's unexpired pending orders and immediately release its held inventory. */
        post: operations["OrdersController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one of the current user's orders. */
        get: operations["OrdersController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notifications for the current user */
        get: operations["NotificationsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current unread notification count */
        get: operations["NotificationsController_unreadCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark one notification as read */
        patch: operations["NotificationsController_markRead"];
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark every notification as read */
        post: operations["NotificationsController_markAllRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/sepay/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** SePay transaction webhook. Idempotently issues tickets on payment. */
        post: operations["PaymentsController_sepayWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan a ticket QR at the gate. Returns VALID / ALREADY_USED / INVALID / WRONG_EVENT (always HTTP 200). */
        post: operations["CheckinController_scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events the current scanner is assigned to. */
        get: operations["ScannerController_listAssigned"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{eventId}/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scanner devices assigned to my event. */
        get: operations["StaffController_list"];
        put?: never;
        /** Create a scanner device for my event; returns its one-time connect code. */
        post: operations["StaffController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/staff/{id}/reconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a fresh one-time connect code for a device; any unredeemed code dies. */
        post: operations["StaffController_reconnect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/staff/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Block/unblock a device or rename its label. */
        patch: operations["StaffController_update"];
        trace?: never;
    };
    "/api/admin/organizers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizers for approval and account management. */
        get: operations["AdminController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizers/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve, block, or restore an organizer account. */
        patch: operations["AdminController_updateStatus"];
        trace?: never;
    };
    "/api/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events for Admin moderation. */
        get: operations["AdminController_listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/events/{id}/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark or unmark a published event as featured. */
        patch: operations["AdminController_updateEventFeatured"];
        trace?: never;
    };
    "/api/admin/events/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve an event waiting for publication review. */
        post: operations["AdminController_approveEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/signature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a signed direct-image upload request */
        post: operations["UploadsController_signature"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify an uploaded image and save its URL */
        post: operations["UploadsController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an uploaded image and clear its saved URL */
        delete: operations["UploadsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get platform-wide sales statistics. */
        get: operations["AdminStatisticsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/statistics/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export a platform-wide revenue CSV report. */
        get: operations["AdminStatisticsController_export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get sales statistics for my events. */
        get: operations["OrganizerStatisticsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/statistics/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export a revenue CSV report for my events. */
        get: operations["OrganizerStatisticsController_export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/withdrawals/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the withdrawable balance from events that have ended. */
        get: operations["WithdrawalsOrganizerController_getBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/withdrawals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the organizer's own withdrawal requests. */
        get: operations["WithdrawalsOrganizerController_list"];
        put?: never;
        /** Submit a withdrawal request for admin review. */
        post: operations["WithdrawalsOrganizerController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/withdrawals/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a withdrawal request still under review. */
        post: operations["WithdrawalsOrganizerController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/withdrawals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List withdrawal requests for manual processing. */
        get: operations["WithdrawalsAdminController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/withdrawals/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a withdrawal request so it can be transferred. */
        post: operations["WithdrawalsAdminController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/withdrawals/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a withdrawal request with a reason. */
        post: operations["WithdrawalsAdminController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/withdrawals/{id}/mark-paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record that the approved amount has been transferred by hand. */
        post: operations["WithdrawalsAdminController_markPaid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example khanh@example.com */
            email: string;
            /** @example matkhau-cua-toi */
            password: string;
            /** @example Huynh Quoc Khanh */
            fullName: string;
            /**
             * @default ATTENDEE
             * @enum {string}
             */
            role: "ATTENDEE" | "ORGANIZER";
            /**
             * @default vi
             * @enum {string}
             */
            locale: "vi" | "en";
        };
        AuthUserDto: {
            id: string;
            email: string | null;
            fullName: string;
            phone: string | null;
            avatarUrl: string | null;
            /** @enum {string} */
            role: "ATTENDEE" | "ORGANIZER" | "SCANNER" | "ADMIN";
            /** @enum {string} */
            status: "ACTIVE" | "PENDING" | "BLOCKED";
            /** @enum {string} */
            locale: "vi" | "en";
        };
        AuthResponseDto: {
            accessToken: string;
            user: components["schemas"]["AuthUserDto"];
        };
        LoginDto: {
            /** @example khanh@example.com */
            email: string;
            /** @example matkhau-cua-toi */
            password: string;
        };
        StaffConnectDto: {
            /**
             * @description One-time connect code
             * @example K7WMPX2Q
             */
            code: string;
        };
        UpdateMeDto: {
            fullName?: string;
            /** @example +84 912 345 678 */
            phone?: string | null;
            /** @enum {string} */
            locale?: "vi" | "en";
        };
        ChangePasswordDto: {
            currentPassword: string;
            newPassword: string;
        };
        EventSummaryDto: {
            /** Format: uuid */
            id: string;
            title: string;
            city: string;
            /** Format: date-time */
            startAt: string;
            coverImageUrl: string | null;
            /** @example 200000 */
            minPriceVnd: number;
            /** @enum {string} */
            category: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
            featured: boolean;
        };
        TicketTypeDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @example 200000 */
            priceVnd: number;
            quantityRemaining: number;
        };
        EventDetailDto: {
            /** Format: uuid */
            id: string;
            title: string;
            city: string;
            /** Format: date-time */
            startAt: string;
            coverImageUrl: string | null;
            /** @example 200000 */
            minPriceVnd: number;
            /** @enum {string} */
            category: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
            featured: boolean;
            description: string;
            venue: string;
            /** Format: date-time */
            endAt: string;
            ticketTypes: components["schemas"]["TicketTypeDto"][];
        };
        OrganizerEventSummaryDto: {
            /** Format: uuid */
            id: string;
            title: string;
            city: string;
            /** @enum {string} */
            category: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
            /** @enum {string} */
            status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "CANCELLED" | "HIDDEN";
            featured: boolean;
            /** Format: date-time */
            startAt: string;
            coverImageUrl: string | null;
            ticketTypeCount: number;
        };
        CreateEventDto: {
            /** @example Live Concert 2026 */
            title: string;
            description: string;
            /** @example Hoa Binh Theatre */
            venue: string;
            /** @example Ha Noi */
            city: string;
            /** @enum {string} */
            category: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
            /**
             * Format: date-time
             * @example 2026-09-01T12:00:00.000Z
             */
            startAt: string;
            /**
             * Format: date-time
             * @example 2026-09-01T15:00:00.000Z
             */
            endAt: string;
        };
        OrganizerTicketTypeDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @example 200000 */
            priceVnd: number;
            quantityTotal: number;
            /** @description Tickets already sold (0 in this slice) */
            soldCount: number;
            /** Format: date-time */
            salesStartAt: string | null;
            /** Format: date-time */
            salesEndAt: string | null;
        };
        OrganizerEventDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizerId: string;
            title: string;
            description: string;
            venue: string;
            city: string;
            /** @enum {string} */
            category: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
            /** @enum {string} */
            status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "CANCELLED" | "HIDDEN";
            featured: boolean;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            coverImageUrl: string | null;
            ticketTypes: components["schemas"]["OrganizerTicketTypeDto"][];
            /** @description Guests admitted so far (USED tickets of the event). */
            checkedInCount: number;
        };
        UpdateEventDto: {
            /** @example Live Concert 2026 */
            title?: string;
            description?: string;
            /** @example Hoa Binh Theatre */
            venue?: string;
            /** @example Ha Noi */
            city?: string;
            /** @enum {string} */
            category?: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
            /**
             * Format: date-time
             * @example 2026-09-01T12:00:00.000Z
             */
            startAt?: string;
            /**
             * Format: date-time
             * @example 2026-09-01T15:00:00.000Z
             */
            endAt?: string;
        };
        CreateTicketTypeDto: {
            /** @example General Admission */
            name: string;
            /**
             * @description VND, integer
             * @example 200000
             */
            priceVnd: number;
            /** @example 500 */
            quantityTotal: number;
            /** Format: date-time */
            salesStartAt?: Record<string, never> | null;
            /** Format: date-time */
            salesEndAt?: Record<string, never> | null;
        };
        UpdateTicketTypeDto: {
            /** @example General Admission */
            name?: string;
            /**
             * @description VND, integer
             * @example 200000
             */
            priceVnd?: number;
            /** @example 500 */
            quantityTotal?: number;
            /** Format: date-time */
            salesStartAt?: Record<string, never> | null;
            /** Format: date-time */
            salesEndAt?: Record<string, never> | null;
        };
        MyTicketDto: {
            /** Format: uuid */
            id: string;
            code: string;
            signature: string;
            /** @description QR payload rendered by the client: `code.signature`. */
            qrPayload: string;
            /** @enum {string} */
            status: "ISSUED" | "USED" | "VOID";
            /** Format: date-time */
            issuedAt: string;
            ticketTypeName: string;
            /** Format: uuid */
            eventId: string;
            eventTitle: string;
            eventVenue: string;
            /** Format: date-time */
            eventStartAt: string;
        };
        CreateOrderItemDto: {
            /** Format: uuid */
            ticketTypeId: string;
            /** @example 2 */
            quantity: number;
        };
        CreateOrderDto: {
            /** Format: uuid */
            eventId: string;
            items: components["schemas"]["CreateOrderItemDto"][];
            /** @description Idempotency key so a retried submission does not order twice. */
            clientRequestId?: string;
        };
        OrderEventDto: {
            /** Format: uuid */
            id: string;
            title: string;
            venue: string;
            /** Format: date-time */
            startAt: string;
        };
        IssuedTicketDto: {
            /** Format: uuid */
            id: string;
            code: string;
            signature: string;
            /** @description QR payload rendered by the client: `code.signature`. */
            qrPayload: string;
            ticketTypeName: string;
            /** @enum {string} */
            status: "ISSUED" | "USED" | "VOID";
        };
        PaymentInfoDto: {
            /** @description Bank short code of the receiving account. */
            bank: string;
            accountNumber: string;
            amountVnd: number;
            /** @description Transfer content the buyer must send verbatim. */
            transferCode: string;
            /** @description VietQR image URL rendered on the checkout screen. */
            qrImageUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        OrderResponseDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "PENDING" | "PAID" | "EXPIRED" | "CANCELLED";
            totalVnd: number;
            /** Format: date-time */
            createdAt: string;
            event: components["schemas"]["OrderEventDto"];
            tickets: components["schemas"]["IssuedTicketDto"][];
            /** @description Present only while the order is PENDING payment. */
            payment?: components["schemas"]["PaymentInfoDto"];
        };
        NotificationDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "TICKET_ISSUED" | "EVENT_SUBMITTED" | "EVENT_APPROVED" | "EVENT_FEATURED" | "PAYMENT_REVIEW_REQUIRED" | "WITHDRAWAL_SUBMITTED" | "WITHDRAWAL_APPROVED" | "WITHDRAWAL_REJECTED" | "WITHDRAWAL_PAID";
            data: {
                [key: string]: unknown;
            } | null;
            read: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        NotificationListDto: {
            items: components["schemas"]["NotificationDto"][];
            total: number;
            unreadCount: number;
            page: number;
            limit: number;
        };
        UnreadNotificationCountDto: {
            count: number;
        };
        SepayWebhookDto: {
            /** @description SePay transaction id; stable across retries. */
            id: number;
            /** @description Amount transferred, in VND. */
            transferAmount: number;
            /** @description Payment code SePay parsed from the transfer content. */
            code?: Record<string, never> | null;
            /** @description Raw transfer content from the bank. */
            content: string;
            /** @description Transfer direction: 'in' or 'out'. */
            transferType: string;
            gateway?: string;
            transactionDate?: string;
            accountNumber?: string;
            accumulated?: number;
            subAccount?: Record<string, never> | null;
            referenceCode?: string;
            description?: string;
        };
        CheckinDto: {
            /** @description Ticket QR payload rendered by the client: `code.signature`. */
            qr: string;
        };
        CheckedInTicketDto: {
            /** Format: uuid */
            id: string;
            ticketTypeName: string;
            sequence: number;
        };
        CheckinResponseDto: {
            /**
             * @description Outcome of the scan; every outcome is a 200 response.
             * @enum {string}
             */
            result: "VALID" | "ALREADY_USED" | "INVALID" | "WRONG_EVENT";
            /** @description Present only when result is VALID. */
            ticket?: components["schemas"]["CheckedInTicketDto"];
            /** @description Guests admitted so far (USED tickets of the event). */
            checkedInCount: number;
        };
        ScannerEventDto: {
            /** Format: uuid */
            id: string;
            title: string;
            venue: string;
            /** Format: date-time */
            startAt: string;
            /** @enum {string} */
            status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "CANCELLED" | "HIDDEN";
        };
        CreateStaffDto: {
            /** @example Gate 1 */
            label: string;
        };
        StaffDeviceDto: {
            /** Format: uuid */
            id: string;
            /** @example Gate 1 */
            label: string;
            /** @enum {string} */
            status: "ACTIVE" | "BLOCKED";
            /** Format: date-time */
            lastScanAt: string | null;
            hasActiveCode: boolean;
        };
        CreateStaffResponseDto: {
            staff: components["schemas"]["StaffDeviceDto"];
            /** @example K7WMPX2Q */
            connectCode: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ReconnectResponseDto: {
            /** @example K7WMPX2Q */
            connectCode: string;
            /** Format: date-time */
            expiresAt: string;
        };
        UpdateStaffDto: {
            /** @enum {string} */
            status?: "ACTIVE" | "BLOCKED";
            /** @example Gate 1 */
            label?: string;
        };
        AdminOrganizerDto: {
            /** Format: uuid */
            id: string;
            email: string | null;
            fullName: string;
            /** @enum {string} */
            status: "ACTIVE" | "PENDING" | "BLOCKED";
            eventCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AdminOrganizerListDto: {
            items: components["schemas"]["AdminOrganizerDto"][];
            total: number;
            page: number;
            limit: number;
        };
        UpdateOrganizerStatusDto: {
            /**
             * @description ACTIVE approves or restores the organizer; BLOCKED revokes access.
             * @enum {string}
             */
            status: "ACTIVE" | "BLOCKED";
        };
        AdminEventDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizerId: string;
            organizerName: string;
            title: string;
            venue: string;
            /** @enum {string} */
            status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "CANCELLED" | "HIDDEN";
            featured: boolean;
            /** Format: date-time */
            startAt: string;
            sold: number;
            capacity: number;
        };
        AdminEventListDto: {
            items: components["schemas"]["AdminEventDto"][];
            total: number;
            page: number;
            limit: number;
        };
        UpdateEventFeaturedDto: {
            featured: boolean;
        };
        UploadRequestDto: {
            /** @enum {string} */
            target: "USER_AVATAR" | "EVENT_COVER";
            /** Format: uuid */
            eventId?: string;
        };
        UploadSignatureDto: {
            uploadUrl: string;
            cloudName: string;
            apiKey: string;
            uploadPreset: string;
            timestamp: number;
            signature: string;
            publicId: string;
            overwrite: boolean;
            invalidate: boolean;
            allowedFormats: string[];
        };
        CompleteUploadRequestDto: {
            /** @enum {string} */
            target: "USER_AVATAR" | "EVENT_COVER";
            /** Format: uuid */
            eventId?: string;
            assetId: string;
            version: number;
        };
        CompleteUploadDto: {
            secureUrl: string;
        };
        SalesStatisticsSummaryDto: {
            paidRevenueVnd: number;
            ticketsSold: number;
            paidOrders: number;
            publishedEvents: number;
        };
        DailySalesStatisticDto: {
            /** @example 2026-08-08 */
            date: string;
            revenueVnd: number;
            ticketsSold: number;
        };
        TopEventStatisticDto: {
            /** Format: uuid */
            id: string;
            title: string;
            revenueVnd: number;
            ticketsSold: number;
            paidOrders: number;
        };
        SalesStatisticsDto: {
            summary: components["schemas"]["SalesStatisticsSummaryDto"];
            daily: components["schemas"]["DailySalesStatisticDto"][];
            topEvents: components["schemas"]["TopEventStatisticDto"][];
        };
        WithdrawalBalanceDto: {
            /** @description Paid revenue from events that have already ended. Revenue from upcoming events is not withdrawable yet. */
            settledRevenueVnd: number;
            /** @description Held by requests that are submitted or approved but not paid. */
            pendingVnd: number;
            /** @description Already transferred out. */
            withdrawnVnd: number;
            /** @description settledRevenueVnd minus pendingVnd and withdrawnVnd. */
            availableVnd: number;
            /** @description Smallest amount a request may ask. */
            minAmountVnd: number;
        };
        WithdrawalDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizerId: string;
            organizerName: string;
            organizerEmail?: string | null;
            /** @description VND, integer */
            amountVnd: number;
            /** @enum {string} */
            status: "PENDING" | "APPROVED" | "PAID" | "REJECTED" | "CANCELLED";
            bankName: string;
            bankAccountNumber: string;
            bankAccountHolder: string;
            organizerNote?: string | null;
            rejectionReason?: string | null;
            transferReference?: string | null;
            adminNote?: string | null;
            /** Format: date-time */
            reviewedAt?: string | null;
            /** Format: date-time */
            paidAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        WithdrawalListDto: {
            items: components["schemas"]["WithdrawalDto"][];
            total: number;
            page: number;
            limit: number;
        };
        CreateWithdrawalDto: {
            /**
             * @description VND, integer
             * @example 500000
             */
            amountVnd: number;
            /** @example Vietcombank */
            bankName: string;
            /** @example 0071000123456 */
            bankAccountNumber: string;
            /** @example HUYNH QUOC KHANH */
            bankAccountHolder: string;
            organizerNote?: string;
        };
        RejectWithdrawalDto: {
            /** @description Shown to the organizer, so it must explain the decision. */
            reason: string;
        };
        MarkWithdrawalPaidDto: {
            /** @description Bank reference of the manual transfer, for reconciliation. */
            transferReference?: string;
            adminNote?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description code: EMAIL_ALREADY_REGISTERED */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description code: INVALID_CREDENTIALS | ACCOUNT_BLOCKED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_staffConnect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffConnectDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description code: INVALID_CONNECT_CODE */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
        };
    };
    AuthController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_findAll: {
        parameters: {
            query?: {
                search?: string;
                city?: string;
                category?: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
                featured?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSummaryDto"][];
                };
            };
        };
    };
    EventsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailDto"];
                };
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventSummaryDto"][];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: INVALID_STATE_TRANSITION */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: EVENT_NOT_PUBLISHABLE | INVALID_STATE_TRANSITION */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_unpublish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: INVALID_STATE_TRANSITION */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: INVALID_STATE_TRANSITION */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_addTicketType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketTypeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_removeTicketType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                typeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: LAST_TICKET_TYPE */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_updateTicketType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                typeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTicketTypeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TicketsController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyTicketDto"][];
                };
            };
        };
    };
    OrdersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
            /** @description EVENT_NOT_PURCHASABLE | PENDING_ORDER_LIMIT_REACHED | SOLD_OUT */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_listPending: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"][];
                };
            };
        };
    };
    OrdersController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description INVALID_STATE_TRANSITION */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListDto"];
                };
            };
        };
    };
    NotificationsController_unreadCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadNotificationCountDto"];
                };
            };
        };
    };
    NotificationsController_markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationDto"];
                };
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_sepayWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SepayWebhookDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description UNAUTHORIZED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CheckinController_scan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckinDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinResponseDto"];
                };
            };
        };
    };
    ScannerController_listAssigned: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannerEventDto"][];
                };
            };
        };
    };
    StaffController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffDeviceDto"][];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StaffController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStaffDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateStaffResponseDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StaffController_reconnect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconnectResponseDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StaffController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStaffDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffDeviceDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_list: {
        parameters: {
            query?: {
                status?: "ACTIVE" | "PENDING" | "BLOCKED";
                /** @description Case-insensitive match against full name or email. */
                search?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrganizerListDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizerStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrganizerDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_listEvents: {
        parameters: {
            query?: {
                status?: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "CANCELLED" | "HIDDEN";
                /** @description Case-insensitive match against event or organizer name. */
                search?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventListDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_updateEventFeatured: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventFeaturedDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_approveEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: INVALID_STATE_TRANSITION */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UploadsController_signature: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSignatureDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: MEDIA_UPLOAD_UNAVAILABLE */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UploadsController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteUploadRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteUploadDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: MEDIA_UPLOAD_FAILED */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: MEDIA_UPLOAD_UNAVAILABLE */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UploadsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadRequestDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: FORBIDDEN_ROLE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: MEDIA_DELETE_FAILED */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: MEDIA_UPLOAD_UNAVAILABLE */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminStatisticsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesStatisticsDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminStatisticsController_export: {
        parameters: {
            query: {
                type: "SUMMARY" | "DETAIL";
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description code: FORBIDDEN_ROLE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizerStatisticsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesStatisticsDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizerStatisticsController_export: {
        parameters: {
            query: {
                type: "SUMMARY" | "DETAIL";
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WithdrawalsOrganizerController_getBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalBalanceDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WithdrawalsOrganizerController_list: {
        parameters: {
            query?: {
                status?: "PENDING" | "APPROVED" | "PAID" | "REJECTED" | "CANCELLED";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalListDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WithdrawalsOrganizerController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWithdrawalDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalDto"];
                };
            };
            /** @description code: VALIDATION_FAILED | WITHDRAWAL_AMOUNT_TOO_SMALL */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: WITHDRAWAL_REQUEST_ALREADY_OPEN | WITHDRAWAL_AMOUNT_EXCEEDS_BALANCE */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WithdrawalsOrganizerController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: INVALID_STATE_TRANSITION */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WithdrawalsAdminController_list: {
        parameters: {
            query?: {
                status?: "PENDING" | "APPROVED" | "PAID" | "REJECTED" | "CANCELLED";
                /** @description Case-insensitive match against organizer name or email. */
                search?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalListDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WithdrawalsAdminController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: INVALID_STATE_TRANSITION */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WithdrawalsAdminController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectWithdrawalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: INVALID_STATE_TRANSITION */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WithdrawalsAdminController_markPaid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkWithdrawalPaidDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: INVALID_STATE_TRANSITION */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
