/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register an account */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List upcoming published events */
        get: operations["EventsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a published event */
        get: operations["EventsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my events (any status) */
        get: operations["EventsOrganizerController_list"];
        put?: never;
        /** Create a draft event */
        post: operations["EventsOrganizerController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one of my events */
        get: operations["EventsOrganizerController_get"];
        put?: never;
        post?: never;
        /** Delete a draft event */
        delete: operations["EventsOrganizerController_remove"];
        options?: never;
        head?: never;
        /** Edit an event (draft or published) */
        patch: operations["EventsOrganizerController_update"];
        trace?: never;
    };
    "/api/organizer/events/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish an event (needs >= 1 ticket type) */
        post: operations["EventsOrganizerController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a published event back to draft */
        post: operations["EventsOrganizerController_unpublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a published event */
        post: operations["EventsOrganizerController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{id}/ticket-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a ticket type */
        post: operations["EventsOrganizerController_addTicketType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{id}/ticket-types/{typeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a ticket type */
        delete: operations["EventsOrganizerController_removeTicketType"];
        options?: never;
        head?: never;
        /** Edit a ticket type */
        patch: operations["EventsOrganizerController_updateTicketType"];
        trace?: never;
    };
    "/api/me/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's issued tickets. */
        get: operations["TicketsController_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an order. Free orders are paid and issued immediately; paid orders return PENDING with VietQR payment details. */
        post: operations["OrdersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one of the current user's orders. */
        get: operations["OrdersController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/sepay/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** SePay transaction webhook. Idempotently issues tickets on payment. */
        post: operations["PaymentsController_sepayWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan a ticket QR at the gate. Returns VALID / ALREADY_USED / INVALID / WRONG_EVENT (always HTTP 200). */
        post: operations["CheckinController_scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events the current scanner is assigned to. */
        get: operations["ScannerController_listAssigned"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example khanh@example.com */
            email: string;
            /** @example matkhau-cua-toi */
            password: string;
            /** @example Huynh Quoc Khanh */
            fullName: string;
            /**
             * @default ATTENDEE
             * @enum {string}
             */
            role: "ATTENDEE" | "ORGANIZER";
        };
        AuthUserDto: {
            id: string;
            email: string;
            fullName: string;
            /** @enum {string} */
            role: "ATTENDEE" | "ORGANIZER" | "SCANNER" | "ADMIN";
            /** @enum {string} */
            status: "ACTIVE" | "PENDING" | "BLOCKED";
        };
        AuthResponseDto: {
            accessToken: string;
            user: components["schemas"]["AuthUserDto"];
        };
        LoginDto: {
            /** @example khanh@example.com */
            email: string;
            /** @example matkhau-cua-toi */
            password: string;
        };
        EventSummaryDto: {
            /** Format: uuid */
            id: string;
            title: string;
            city: string;
            /** Format: date-time */
            startAt: string;
            coverImageUrl: string | null;
            /** @example 200000 */
            minPriceVnd: number;
            /** @enum {string} */
            category: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
            featured: boolean;
        };
        TicketTypeDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @example 200000 */
            priceVnd: number;
            quantityRemaining: number;
        };
        EventDetailDto: {
            /** Format: uuid */
            id: string;
            title: string;
            city: string;
            /** Format: date-time */
            startAt: string;
            coverImageUrl: string | null;
            /** @example 200000 */
            minPriceVnd: number;
            /** @enum {string} */
            category: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
            featured: boolean;
            description: string;
            venue: string;
            /** Format: date-time */
            endAt: string;
            ticketTypes: components["schemas"]["TicketTypeDto"][];
        };
        OrganizerEventSummaryDto: {
            /** Format: uuid */
            id: string;
            title: string;
            city: string;
            /** @enum {string} */
            category: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED" | "HIDDEN";
            featured: boolean;
            /** Format: date-time */
            startAt: string;
            coverImageUrl: string | null;
            ticketTypeCount: number;
        };
        CreateEventDto: {
            /** @example Live Concert 2026 */
            title: string;
            description: string;
            /** @example Hoa Binh Theatre */
            venue: string;
            /** @example Ha Noi */
            city: string;
            /** @enum {string} */
            category: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
            /**
             * Format: date-time
             * @example 2026-09-01T12:00:00.000Z
             */
            startAt: string;
            /**
             * Format: date-time
             * @example 2026-09-01T15:00:00.000Z
             */
            endAt: string;
            coverImageUrl?: string | null;
            /** @default false */
            featured: boolean;
        };
        OrganizerTicketTypeDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @example 200000 */
            priceVnd: number;
            quantityTotal: number;
            /** @description Tickets already sold (0 in this slice) */
            soldCount: number;
            /** Format: date-time */
            salesStartAt: string | null;
            /** Format: date-time */
            salesEndAt: string | null;
        };
        OrganizerEventDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizerId: string;
            title: string;
            description: string;
            venue: string;
            city: string;
            /** @enum {string} */
            category: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED" | "HIDDEN";
            featured: boolean;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            coverImageUrl: string | null;
            ticketTypes: components["schemas"]["OrganizerTicketTypeDto"][];
            /** @description Guests admitted so far (USED tickets of the event). */
            checkedInCount: number;
        };
        UpdateEventDto: {
            /** @example Live Concert 2026 */
            title?: string;
            description?: string;
            /** @example Hoa Binh Theatre */
            venue?: string;
            /** @example Ha Noi */
            city?: string;
            /** @enum {string} */
            category?: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
            /**
             * Format: date-time
             * @example 2026-09-01T12:00:00.000Z
             */
            startAt?: string;
            /**
             * Format: date-time
             * @example 2026-09-01T15:00:00.000Z
             */
            endAt?: string;
            coverImageUrl?: string | null;
            /** @default false */
            featured: boolean;
        };
        CreateTicketTypeDto: {
            /** @example General Admission */
            name: string;
            /**
             * @description VND, integer
             * @example 200000
             */
            priceVnd: number;
            /** @example 500 */
            quantityTotal: number;
            /** Format: date-time */
            salesStartAt?: Record<string, never> | null;
            /** Format: date-time */
            salesEndAt?: Record<string, never> | null;
        };
        UpdateTicketTypeDto: {
            /** @example General Admission */
            name?: string;
            /**
             * @description VND, integer
             * @example 200000
             */
            priceVnd?: number;
            /** @example 500 */
            quantityTotal?: number;
            /** Format: date-time */
            salesStartAt?: Record<string, never> | null;
            /** Format: date-time */
            salesEndAt?: Record<string, never> | null;
        };
        MyTicketDto: {
            /** Format: uuid */
            id: string;
            code: string;
            signature: string;
            /** @description QR payload rendered by the client: `code.signature`. */
            qrPayload: string;
            /** @enum {string} */
            status: "ISSUED" | "USED" | "VOID";
            /** Format: date-time */
            issuedAt: string;
            ticketTypeName: string;
            /** Format: uuid */
            eventId: string;
            eventTitle: string;
            eventVenue: string;
            /** Format: date-time */
            eventStartAt: string;
        };
        CreateOrderItemDto: {
            /** Format: uuid */
            ticketTypeId: string;
            /** @example 2 */
            quantity: number;
        };
        CreateOrderDto: {
            /** Format: uuid */
            eventId: string;
            items: components["schemas"]["CreateOrderItemDto"][];
            /** @description Idempotency key so a retried submission does not order twice. */
            clientRequestId?: string;
        };
        OrderEventDto: {
            /** Format: uuid */
            id: string;
            title: string;
            venue: string;
            /** Format: date-time */
            startAt: string;
        };
        IssuedTicketDto: {
            /** Format: uuid */
            id: string;
            code: string;
            signature: string;
            /** @description QR payload rendered by the client: `code.signature`. */
            qrPayload: string;
            ticketTypeName: string;
            /** @enum {string} */
            status: "ISSUED" | "USED" | "VOID";
        };
        PaymentInfoDto: {
            /** @description Bank short code of the receiving account. */
            bank: string;
            accountNumber: string;
            amountVnd: number;
            /** @description Transfer content the buyer must send verbatim. */
            transferCode: string;
            /** @description VietQR image URL rendered on the checkout screen. */
            qrImageUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        OrderResponseDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "PENDING" | "PAID" | "EXPIRED" | "CANCELLED";
            totalVnd: number;
            /** Format: date-time */
            createdAt: string;
            event: components["schemas"]["OrderEventDto"];
            tickets: components["schemas"]["IssuedTicketDto"][];
            /** @description Present only while the order is PENDING payment. */
            payment?: components["schemas"]["PaymentInfoDto"];
        };
        SepayWebhookDto: {
            /** @description SePay transaction id; stable across retries. */
            id: number;
            /** @description Amount transferred, in VND. */
            transferAmount: number;
            /** @description Payment code SePay parsed from the transfer content. */
            code?: Record<string, never> | null;
            /** @description Raw transfer content from the bank. */
            content: string;
            /** @description Transfer direction: 'in' or 'out'. */
            transferType: string;
            gateway?: string;
            transactionDate?: string;
            accountNumber?: string;
            accumulated?: number;
            subAccount?: Record<string, never> | null;
            referenceCode?: string;
            description?: string;
        };
        CheckinDto: {
            /** @description Ticket QR payload rendered by the client: `code.signature`. */
            qr: string;
        };
        CheckedInTicketDto: {
            /** Format: uuid */
            id: string;
            ticketTypeName: string;
            sequence: number;
        };
        CheckinResponseDto: {
            /**
             * @description Outcome of the scan; every outcome is a 200 response.
             * @enum {string}
             */
            result: "VALID" | "ALREADY_USED" | "INVALID" | "WRONG_EVENT";
            /** @description Present only when result is VALID. */
            ticket?: components["schemas"]["CheckedInTicketDto"];
            /** @description Guests admitted so far (USED tickets of the event). */
            checkedInCount: number;
        };
        ScannerEventDto: {
            /** Format: uuid */
            id: string;
            title: string;
            venue: string;
            /** Format: date-time */
            startAt: string;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED" | "HIDDEN";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description code: EMAIL_ALREADY_REGISTERED */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description code: INVALID_CREDENTIALS | ACCOUNT_BLOCKED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    EventsController_findAll: {
        parameters: {
            query?: {
                search?: string;
                city?: string;
                category?: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
                featured?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSummaryDto"][];
                };
            };
        };
    };
    EventsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailDto"];
                };
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventSummaryDto"][];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: INVALID_STATE_TRANSITION */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: EVENT_NOT_PUBLISHABLE | INVALID_STATE_TRANSITION */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_unpublish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: INVALID_STATE_TRANSITION */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: INVALID_STATE_TRANSITION */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_addTicketType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketTypeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_removeTicketType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                typeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: LAST_TICKET_TYPE */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsOrganizerController_updateTicketType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                typeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTicketTypeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerEventDto"];
                };
            };
            /** @description code: FORBIDDEN_ROLE | ACCOUNT_PENDING_APPROVAL */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TicketsController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyTicketDto"][];
                };
            };
        };
    };
    OrdersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
            /** @description EVENT_NOT_PURCHASABLE | SOLD_OUT */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_sepayWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SepayWebhookDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description UNAUTHORIZED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CheckinController_scan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckinDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinResponseDto"];
                };
            };
        };
    };
    ScannerController_listAssigned: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannerEventDto"][];
                };
            };
        };
    };
}
