/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register an account */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List upcoming published events */
        get: operations["EventsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a published event */
        get: operations["EventsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example khanh@example.com */
            email: string;
            /** @example matkhau-cua-toi */
            password: string;
            /** @example Huynh Quoc Khanh */
            fullName: string;
            /**
             * @default ATTENDEE
             * @enum {string}
             */
            role: "ATTENDEE" | "ORGANIZER";
        };
        AuthUserDto: {
            id: string;
            email: string;
            fullName: string;
            /** @enum {string} */
            role: "ATTENDEE" | "ORGANIZER" | "SCANNER" | "ADMIN";
            /** @enum {string} */
            status: "ACTIVE" | "PENDING" | "BLOCKED";
        };
        AuthResponseDto: {
            accessToken: string;
            user: components["schemas"]["AuthUserDto"];
        };
        LoginDto: {
            /** @example khanh@example.com */
            email: string;
            /** @example matkhau-cua-toi */
            password: string;
        };
        EventSummaryDto: {
            /** Format: uuid */
            id: string;
            title: string;
            city: string;
            /** Format: date-time */
            startAt: string;
            coverImageUrl: string | null;
            /** @example 200000 */
            minPriceVnd: number;
            /** @enum {string} */
            category: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
            featured: boolean;
        };
        TicketTypeDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @example 200000 */
            priceVnd: number;
            quantityRemaining: number;
        };
        EventDetailDto: {
            /** Format: uuid */
            id: string;
            title: string;
            city: string;
            /** Format: date-time */
            startAt: string;
            coverImageUrl: string | null;
            /** @example 200000 */
            minPriceVnd: number;
            /** @enum {string} */
            category: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
            featured: boolean;
            description: string;
            venue: string;
            /** Format: date-time */
            endAt: string;
            ticketTypes: components["schemas"]["TicketTypeDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description code: EMAIL_ALREADY_REGISTERED */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description code: INVALID_CREDENTIALS | ACCOUNT_BLOCKED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    EventsController_findAll: {
        parameters: {
            query?: {
                search?: string;
                city?: string;
                category?: "MUSIC" | "TECH" | "ART" | "SPORT" | "WORKSHOP";
                featured?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSummaryDto"][];
                };
            };
        };
    };
    EventsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailDto"];
                };
            };
            /** @description code: NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
