/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'media',
  theme: {
    extend: {
      colors: {
        primary: '#006b5f',
        'on-primary': '#ffffff',
        'primary-container': '#14b8a6',
        'on-primary-container': '#00423b',
        secondary: '#a93349',
        'on-secondary': '#ffffff',
        'secondary-container': '#fe7488',
        'on-secondary-container': '#730425',
        tertiary: '#9b4426',
        'tertiary-container': '#f38764',
        'on-tertiary-container': '#6c2106',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        success: '#0f7350',
        'on-success': '#ffffff',
        'success-container': '#a6f2ce',
        'on-success-container': '#00382a',
        warning: '#8a5300',
        'on-warning': '#ffffff',
        'warning-container': '#ffddb3',
        'on-warning-container': '#2c1700',
        surface: '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e6eeff',
        'surface-container-high': '#dee9fc',
        'on-surface': '#121c2a',
        'on-surface-variant': '#3c4947',
        outline: '#6c7a77',
        'outline-variant': '#bbcac6',

        // Dark mode tokens. Mirror `colorsDark` in DESIGN.md.
        'd-primary': '#4fdbc8',
        'd-on-primary': '#00382f',
        'd-surface': '#101720',
        'd-surface-container': '#1d232c',
        'd-surface-container-lowest': '#0b1119',
        'd-on-surface': '#dfe3ec',
        'd-on-surface-variant': '#bfc9c6',
        'd-outline': '#899490',
        'd-outline-variant': '#3c4947',
        'd-error': '#ffb4ab',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        md: '0.75rem', // input
        lg: '1rem', // card
        xl: '1.5rem',
        full: '9999px', // button
      },
      spacing: {
        'container-padding': '20px',
        gutter: '16px',
        'touch-target-min': '48px',
        'cta-height': '52px',
      },
      fontFamily: {
        sans: ['BeVietnamPro_400Regular'],
        medium: ['BeVietnamPro_500Medium'],
        semibold: ['BeVietnamPro_600SemiBold'],
        bold: ['BeVietnamPro_700Bold'],
      },
    },
  },
  plugins: [],
};
